version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estrutura-clean-ddd-api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8080:8000"
    command: >
      sh -lc "
        composer install &&
        ([ -f .env ] || cp .env.example .env) &&
        php artisan key:generate &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: estrutura-clean-ddd-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
